### ISSUE TITLE
Broken LGStarterKit.Site project because of old targets

### ISSUE THREAD

**Issue by jamesquox** [KevinJump/LocalGovStarterKit#2]
Hi Kevin & everyone else,

I cloned this project and spent a while trying to find out why it would not build.
Turns out the project file here (https://github.com/KevinJump/LocalGovStarterKit/blob/master/LGStarterKit.Site/LGStarterKit.Site.csproj) has the build targets for the old version of UmbracoCms.7.2.6

If you remove the following line numbers from the file it builds as it should:
477 `<Error Condition="!Exists('..\packages\UmbracoCms.7.2.6\build\UmbracoCms.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\UmbracoCms.7.2.6\build\UmbracoCms.props'))" />`
 488   `<Error Condition="!Exists('..\packages\UmbracoCms.7.2.6\build\UmbracoCms.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\UmbracoCms.7.2.6\build\UmbracoCms.targets'))" />`
452  `<Import Project="..\packages\UmbracoCms.7.2.6\build\UmbracoCms.targets" Condition="Exists('..\packages\UmbracoCms.7.2.6\build\UmbracoCms.targets')" />`

Not a fault on Kevins part - just Nuget getting confused as usual.

Thanks.

**Comment by KevinJump** [comment]
thanks, 

just checking the latest upgrade to v7.5.0 cleared these out for me : ) (in the v6-main branch which is now default)
