### ISSUE TITLE
Error: Nav/GatewayLinks.cshtml is missing in 7.5.0

### ISSUE THREAD

**Issue by ibrolive** [KevinJump/LocalGovStarterKit#6]
Hi,

I installed the LGStarterKit_6.0.2.zip package and after creating a homepage, and saving and publishing the page, I tried to view the page, and got an error (see the screenshot):

![image](https://cloud.githubusercontent.com/assets/6414095/17831811/a08cc71c-66eb-11e6-8322-0dcca642395b.png)

**Comment by KevinJump** [comment]
Hi 

I can't reproduce this, Umbraco 7.5 fresh install, starter kit 6.0.2 

when i install and create the homepage, this works and the GatewayLinks.cshtml file is in views/partials/nav/gatewaylinks.cshtml

can you check on disk, and report back on what is in the views/partials folder on your install?

**Comment by ibrolive** [comment]
Hi Kevin,

Thanks for your feedback on this.

With your feedback confirming this works well "Out of The Box", I decided to do a little more digging, and figured out that this was related to Umbraco and not the package.

Umbrage doesn’t seem to like a Virtual Directory deployment. I was getting errors because my deployment was in a virtual directory (see attached screenshot below, error page is displayed after package deployment).

I moved the files from Virtual Directory to the site root level, and all was well again.

Thanks a lot. Excellent starter kit by the way!

Kind Regards,
Ibrahim Dauda,
Software / Database / Application Support
http://igmbhost.com/ http://igmbhost.com/ - Hosting you can trust!
Mobile: +234 810 364 5222, +234 701 870 9455
Skype: ibrolive

**Comment by KevinJump** [comment]
Cool,

glad you got it working.
